name: ollama_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11.7
  - pip:
    - python-telegram-bot
    - ollama
    - nest_asyncio
    # - openai
    - tiktoken
    - PyYAML
    - pymongo
    - python-dotenv
